### PR TITLE
update geekdoc theme to v0.24.0

### PR DESCRIPTION
**Pull request by mbkma**

### CODE REVIEW

**Comment by raveit65** [comment]
Any chance to see the result of the PR before pushing to master?
Eg. to built the hugo CSM locally. (how?)
Edit:
Or can we trust the deployment?

**Comment by mbkma** [comment]
yes, it is very easy:
1. `sudo dnf install hugo`
2. Go to mate-wiki directory
3. Run `hugo server` inside that directory
(see https://developer.fedoraproject.org/start/sw/web-app/hugo.html for reference)

For now the deployment just makes sure that hugo can build the website correctly. To check for theming/content/... issues a preview would be nice that is done by https://github.com/mate-desktop/mate-wiki/pull/8)

**Comment by mbkma** [comment]
yes, its is very easy:
1. `sudo dnf install hugo`
2. Go to mate-wiki directory
3. Run `hugo server` inside that directory
(see https://developer.fedoraproject.org/start/sw/web-app/hugo.html for reference)

**Review by raveit65 — APPROVED** [review]
LGTM,
new version of geekdoc theme runs fine locally.

**Comment by raveit65** [comment]
> yes, its is very easy:
> 
>     1. `sudo dnf install hugo`
> 
>     2. Go to mate-wiki directory
> 
>     3. Run `hugo server` inside that directory
>        (see https://developer.fedoraproject.org/start/sw/web-app/hugo.html for reference)
> 
> 
> For now the deployment just makes sure that hugo can build the website correctly. To check for theming/content/... issues a preview would be nice that is done by #8)

hehe, that is easy :)

**Pull request merged**
