### PR TITLE
Update contributing.ja.md

### PR DESCRIPTION
**Pull request by usergreen**
Fix translation and add new translated pages in Japanese

### CODE REVIEW

**Comment by usergreen** [comment]
I wonder if this commit needs ssh connection or not. Because I have not experienced uploading errors like this in the past. Has Github specifications or policy changed recently?

**Comment by usergreen** [comment]
Here's another question. Do I have to rename atril.md as atril.ja.md, for example? Or renaming is not required for mate-wiki?

**Comment by mbkma** [comment]
No you dont need to rename it to atril.ja.md. We use Translation by content directory see https://gohugo.io/content-management/multilingual/#translation-by-content-directory. I think your commits are fine, I just fixed the checks, see https://github.com/mate-desktop/mate-wiki/pull/24.

**Comment by mbkma** [comment]
In the future you can add all your changes in just one commit with the title "Update Japanese translation." This leads to a cleaner git commit history.

**Comment by usergreen** [comment]
I see. Thank you.

**Comment by mbkma** [comment]
Could you rebase this commits into one please?
`git rebase -i HEAD~6`
And then squash all commits into the first one, and rename this commit to `Update Japanese translation`.

**Comment by usergreen** [comment]
I submitted this PR as #26 ( https://github.com/mate-desktop/mate-wiki/pull/26 ).

**Pull request closed without merging**
