### PR TITLE
mozo has meson support

### PR DESCRIPTION
**Pull request by mbkma**

### CODE REVIEW

**Review by raveit65 — APPROVED** [review]
LGTM,
deployment process runs fine.
No idea to test change without a review.

**Comment by mbkma** [comment]
@raveit can you check if at mate-wiki-old if github pages is still set to https://wiki.mate-desktop.org/  and if so can you remove it? Because the the deployment link here gets reset every time there is a commit.

**Comment by raveit65** [comment]
Gh-pages is currently disabled for mate-wiki-old
Bildschirmfoto zu 2021-09-03 19-28-26
Should i move mate-wiki-old to Mate-legacy? https://github.com/mate-desktop-legacy-archive
Undo this action is always possible.

**Comment by mbkma** [comment]
Yes, I think you should do that.

**Comment by raveit65** [comment]
@mbkma 
Done, i just moved mate-wiki-old and mate-wiki-preview to legacy https://github.com/mate-desktop-legacy-archive

**Pull request merged**
