### PR TITLE
update github workflows

### PR DESCRIPTION
**Pull request by mbkma**
With this, PR previews should actually work.

### CODE REVIEW

**Comment by mbkma** [comment]
We can delete https://github.com/mate-desktop/mate-wiki-preview with this PR.

**Comment by mbkma** [comment]
If no one likes to review I am going to merge these, as they are not critical and only concern the wiki.

**Comment by raveit65** [comment]
We got a reviewer problem since years. Everybody needs to review other open reviews, otherwise this system doesn't work.
Still wondering that you ask for a rush review after we didn't hear from you since a year.
Any way, preview is working, go ahead.
I don't have the time and interest to read documents how wiki CMS and github deployment is working.

**Review by raveit65 — COMMENTED** [review]
Preview is working

**Review by raveit65 — APPROVED** [review]

**Pull request merged**
