### PR TITLE
Add _index.ja.md for MATE Wiki website

### PR DESCRIPTION
**Pull request by usergreen**
I added _index.ja.md to MATE Wiki for Japanese language support.

### CODE REVIEW

**Comment by raveit65** [comment]
I am not really sure how different language support should work on wiki page.
From technical view is is another website and language selecting from mate-desktop website doesn't work here.

**Comment by usergreen** [comment]
Are you going to add pages in other languages, don't you? In old MATE Wiki page, I read a description that you could make pages by adding language code to a certain page.md like "sample.fr.md".

What about our new Wiki site? I am not sure for our policy, but for example, many pages are available in different languages in https://fedoraproject.org/wiki/Fedora_Project_Wiki If language selecting doesn't work there, I think it is alright to simply add pages.

**Comment by raveit65** [comment]
The questions is not to add different languages, the question is how to make language selection working.

**Comment by usergreen** [comment]
How about just simply add hyperlinks in individual articles, instead of considering to function language selector? I think mate-desktop.org is the main site, and mate-wiki is an archive of documentation.

This may be an easier way. And also wiki-users usually use "wiki-links" inside their wiki-sites.

**Comment by raveit65** [comment]
Well, it isn't nice that mate-wiki isn't translated.
But i don't want to rewrite 2 websites at the moment.
Just leave the PR open we will find a solution.

**Comment by mbkma** [comment]
Just for reference: https://gohugo.io/content-management/multilingual/
I will look into that when I have more time.

**Comment by mbkma** [comment]
with the new geekdoc version (see https://github.com/mate-desktop/mate-wiki/pull/7) multiple languages, i.e. translation of the mate-wiki, will be supported.

**Comment by usergreen** [comment]
Thank you mbkma,
I misunderstood until now that this wiki is frozen to edit from the login on the top page, and translations  must be done only through Transifex.
Thanks again!

**Pull request closed without merging**
