### PR TITLE
Add Solus section

### PR DESCRIPTION
**Pull request by Drsheppard01**

### CODE REVIEW

**Comment by raveit65** [comment]
Hmm, i don't see the new entry in preview https://wiki.mate-desktop.dev/introduction/installation/

@mbkma 
I guess we see only the preview of the last PR and every new PR will override the deployment, right?
And do we need rebase from master to fix the deployment issue?

**Comment by raveit65** [comment]
`git merge` isn't the same like the `git rebase` command, but i think we get out the annoying merge commit with squashing all commits when merging.
Any way, deployment failed.

**Comment by mbkma** [comment]
Deployment fails because of this error:   `Error: Action failed with "not found deploy key or tokens"` in the `Deploy Website` step.
I have to figure out why this happens.

**Comment by mbkma** [comment]
@Drsheppard01 why closing the PR?

**Comment by Drsheppard01** [comment]
> 

If I understand correctly, it can't be assembled because I didn't sync with the upstream of the latest version

Perhaps this is also due to the division of the content directory into "en" and "ja"

**Comment by Drsheppard01** [comment]
@mbkma what should i do to make it sync or i dont have to do anything?

**Comment by mbkma** [comment]
no, you did nothing wrong :) the website builded fine, just the deployment to our preview website failed. Probably because there is something wrong with our keys. It would be great if you could make the same PR again :)

**Pull request closed without merging**
