### PR TITLE
Add translated pages in Japanese

### PR DESCRIPTION
**Pull request by usergreen**
Thank you mbkma,
I misunderstood until now that this wiki is frozen to edit from the login on the top page, and translations must be done only through Transifex.
Thanks again!

### CODE REVIEW

**Comment by usergreen** [comment]
Added ja.jaym, too

**Comment by mbkma** [comment]
@usergreen  I made another PR #21 with your commits and fixed a few errors.

**Comment by mbkma** [comment]
@usergreen I think for this file https://github.com/mate-desktop/mate-wiki/pull/17/files#diff-9561bea3e8b1e68da8b73fe590dbfd73f04f6a96a1437cb3cc3f894baa5992f8 you should make a PR at https://github.com/thegeeklab/hugo-geekdoc

**Comment by usergreen** [comment]
Thank you, mbkma
I have just made a PR at https://github.com/thegeeklab/hugo-geekdoc/pull/471

**Comment by usergreen** [comment]
The PR #471 was adopted as #475.
FYR, please see https://github.com/thegeeklab/hugo-geekdoc/pull/475

**Comment by mbkma** [comment]
perfect, we then just wait for a new release of hugo-geekdoc to incorporate your changes to the mate-wiki.

**Pull request closed without merging**
