### PR TITLE
Update wayland-meson.md

### PR DESCRIPTION
**Pull request by lukefromdc**
Show that caja now supports wayland as the relevent commits have been merged to master

### CODE REVIEW

**Comment by raveit65** [comment]
Support without been able to move the browser window is very optimistic.
Caja has the the same problem inside mir compositor.
But Ok, we can merge this if you want.

**Comment by lukefromdc** [comment]
We can also hold this pending a browser window fix if you want, but "not started" is also incorrect given how much has been done. If an "in progress" option exists we could use that now and change it when a fix for moving the browser window the normal way in compositors defaulting to CSD is found

**Comment by raveit65** [comment]
Is it really CSD? I am using Menta theme and it looks like a normal decoration with min/max/close button.
But without any typical CSD menu buttons.

**Comment by lukefromdc** [comment]
It is indeed a type of CSD, though without the big GtkHeaderBar if the app doesn't use it. It uses the GTK theme to draw the decorations thus looks a lot like Metacity. You should see almost the same appearance in metacity and in wayfire with  "perfer client side" set.

NOT sure how it works, I have found at least two apps with windows that are hard to move: In addition to caja with "prefer client side" set, Audacious with it's classical shell cannot be dragged by it's edges. It's in xwayland and we still get this and in the case of Audacious it's regardless of the decoration mode set as Audacious itself in the classic shell is undecorated with it's own draggable areas set inside the app.

Note that nautilus windows CAN be dragged in CSD mode though no special CSD support is in the code. So can pluma and mate-terminal, so we are doing something odd in Caja and I have yet to find it

**Comment by raveit65** [comment]
Hmm, i didn't know that. So, all window decorations under wayfire, mir like caja --browser or mate-terminal are CSD Windows? 
They don't look like client-side-decoration.
decorations_wayfire

But ok, i do not really know much about wayland and GTK.

**Review by raveit65 — APPROVED** [review]
Caja runs under wayland. Not all functions are working now.
Let' go.

**Pull request merged**
